FROM jetty:9.3.10

MAINTAINER Robert Kaye <rob@metabrainz.org>

ENV SEARCH_HOME=/home/search
ENV INDEXES_VERSION=1
ENV RSYNC_SERVER=search-indexer 
ENV RSYNC_PASSWORD=search

RUN apt-get update && apt-get install -y --no-install-recommends \
        bsdmainutils \
        psmisc \
        python \
        rsync

WORKDIR $JETTY_HOME

# Install the war file
RUN curl -o $JETTY_HOME/webapps/ROOT.war ftp://ftp.eu.metabrainz.org/pub/musicbrainz/search/servlet/searchserver.war 

# Install dumb-init
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64
RUN chmod +x /usr/local/bin/dumb-init

# Install the watcher script
ADD bin/server-entrypoint.sh /

# Setup the data volumes/dirs
VOLUME ["/home/search/indexes"]

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["/server-entrypoint.sh", "/home/search/data/new/RELOAD", "/docker-entrypoint.sh", "java","-jar","/usr/local/jetty/start.jar"]
